### ISSUE TITLE
Replace context data from session to current_user

### ISSUE THREAD

**Issue by s0b0lev** [sloria/cookiecutter-flask#119]
This part use **session** to take data about username, so it return empty value. I think it session should be replaced with **current_user**.

https://github.com/sloria/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/templates/users/members.html#L4

**Comment by sloria** [comment]
I think you're right. I would certainly review and merge a PR for this. =)
