### ISSUE TITLE
Flask test >> no such command

### ISSUE THREAD

**Issue by lippytak** [sloria/cookiecutter-flask#127]
I followed the instructions in the https://github.com/sloria/cookiecutter-flask readme and then the project generated readme. Now running `flask test` is an unrecognized command:

```sh
✗ flask test
Usage: flask [OPTIONS] COMMAND [ARGS]...

Error: No such command "test".
```

Any ideas? I'm sure I missed something obvious...

**Comment by MatanSilver** [comment]
I have this problem with all of the commands listed in commands.py, and when I try to add my own commands. For some reason the calls in register_commands in app.py aren't working properly but I haven't been able to figure out why.

**Comment by Jaza** [comment]
Have you set `export FLASK_APP=/path/to/autoapp.py` ?? Since flask-cookiecutter was upgraded to Flask 0.11 and was modified to use Click instead of Flask-Script, this has become a required step, none of the commands defined in commands.py will work without it.

**Comment by MatanSilver** [comment]
Turns out the problem for me was I had just `autoapp.py` and not the full path. Hopefully that works for @lippytak too.
