### ISSUE TITLE
Git origin - upstream

### ISSUE THREAD

**Issue by marcmmx** [sloria/cookiecutter-flask#131]
Hi, usually I work with origin and upstream from Git. How does this fit with cookiecutter. How can I benefit from updates on cookiecutter-flask without using origin and upstream functionality. Thanks.

**Comment by sloria** [comment]
Do you mean you want to update your already-generated project with the latest changes from cookiecutter-flask? I'm not sure of a nice, automated way to achieve this. Your best bet is to manually port the changes on cookiecutter-flask to your project.
