### ISSUE TITLE
Errors while trying to add Flask-User ext

### ISSUE THREAD

**Issue by satishvis** [sloria/cookiecutter-flask#181]
When I try to add Flask User. Something to do with SQLAlchemyAdapter. db gets problematic and not able to be imported in the database.py

**Comment by thuvh** [comment]
I think this is an issue of Flask-User. Normally, if you use this template to create an application and want to add an extension of the flask to your project, you have to create an object in extensions.py and call init_app in app.py. However, after reading two examples from the document of Flask-User, I think I can not follow the convention as I said above.

**Comment by sloria** [comment]
Closing, as this issue is stale. Feel free to reopen or comment if there's still an issue.
