### ISSUE TITLE
(index):72 Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by tanyewei** [sloria/cookiecutter-flask#185]
new webpack.ProvidePlugin({ $: 'jquery',
                                jQuery: 'jquery' }),

**Comment by sbhtw** [comment]
`new webpack.ProvidePlugin({ '$': 'jquery',
                            jQuery: 'jquery' }),`

**Comment by wonderbred** [comment]
I was getting the same error using the eonasdan-bootstrap-datetimepicker widget.

I tried several things, including adding the last two lines here to the ProvidePlugin section of webpack.config.js:
```javascript
    new webpack.ProvidePlugin({ $: 'jquery',
                                jQuery: 'jquery',
                                'window.$': 'jquery',
                                'window.jQuery': 'jquery' }),
```

The only thing that actually worked, however, was changing `require('jquery');` in main.js to this:
```javascript
window.$ = window.jQuery = require('jquery');
```

This might not be ideal, though. Does anyone have a better solution?

**Comment by dylanjnz** [comment]
I was able to get this resolved by adding the expose-loader, and specifying this as the loader in the exports:

`npm i expose-loader -s`

And then in 

```
module: { 
  loaders { 
    ... 
    { test: require.resolve('jquery'), loaders: ['expose-loader?$', 'expose-loader?jQuery'] },
```

**Comment by wonderbred** [comment]
This worked for me and seems like a much cleaner solution.

Thanks, @dylanjnz !

**Comment by sloria** [comment]
Closing, as this issue is stale. Feel free to reopen or comment if there's still an issue.
