### ISSUE TITLE
Guide for deployment on PythonAnywhere

### ISSUE THREAD

**Issue by zerox1212** [sloria/cookiecutter-flask#187]
Is there any chance someone can give me a brief step by step on getting this to run on Python Anywhere?

It would be nice to get a guide like https://github.com/pydanny/cookiecutter-django/blob/master/docs/deployment-on-pythonanywhere.rst .

**Comment by zerox1212** [comment]
If someone could confirm what is require to run this on Windows that would also be helpful.

So far it looks like you at least need:
Python
npm (node package manager)
node.js (because this web app uses webpack)

**Comment by sloria** [comment]
I have not used PythonAnywhere. I would certainly merge a PR updating the docs though.

**Comment by zerox1212** [comment]
If I ever get it to work I will see if I can write something, but so far I'm really struggling with my first web app, which I am a bit surprised by because I know python well. The amount of dependencies just to get a boilerplate web app with login running seems crazy.

**Comment by zerox1212** [comment]
I have to give up on this one. I got the project loaded up on Python Anywhere, ran `npm install` to setup webpack, but after that I can't get any of the flask commands, despite `.bashrc' having the path to the app.

Always get this:  
`(x-virtualenv) 01:43 ~ $ flask db init
Usage: flask db init [OPTIONS]
Error: The file/path provided (site/mydir/autoapp.py) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py`

**Comment by vousmeevoyez** [comment]
Since no documentation on the project, i've write my own documentation on how to deploy your project to pythonanywhere.

https://dev.to/vousmeevoyez/deploying-cookiecutter-flask-for-free-using-pythonanywhere-500m
