### ISSUE TITLE
Pycharm Debugging Support

### ISSUE THREAD

**Issue by patvin80** [sloria/cookiecutter-flask#215]
Hello 

I was trying to get Pycharm debugging support for the application and found this link:
http://favstar.fm/users/corbinbs/status/71947595169280000

I added the line in the autoapp.py file and set my debug configuration to run the python file.

I am trying to understand what are the implications of such change.

Regards
Vinit

**Comment by sloria** [comment]
Closing, as this issue has gone stale. Feel free to reopen if you're still having issues

**Comment by luismanson** [comment]
Link is dead, did it work?? Do you remember what it was? 
Thanks

**Comment by jamescurtin** [comment]
I do not develop in Pycharm, but the [Flask Docs](https://flask.palletsprojects.com/en/1.1.x/cli/#pycharm-integration) provide a good starting place. But you'd also need to remember to start up the webpack dev server for the static content.
