### ISSUE TITLE
Webpack integration: webpack-dev-server crashes after a few seconds

### ISSUE THREAD

**Issue by khoffrath** [sloria/cookiecutter-flask#218]
Hi!

I'm encountering problems using the new webpack integration:

After setting up a test project (steps see below) and executing "npm start" the webpack and flask processes are coming up, I can open the website in a browser and everything appears to be working. However, after a few seconds the webpack-dev-server exits with the following error log:

> [WEBPACK] /Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/manifest-revision-webpack-plugin/format.js:52
[WEBPACK]             var fileExtension = asset.split('.').slice(-1)[0];
[WEBPACK]                                       ^
[WEBPACK]
[WEBPACK] TypeError: asset.split is not a function
[WEBPACK]     at Format.mergeChunksIntoAssets (/Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/manifest-revision-webpack-plugin/format.js:52:39)
[WEBPACK]     at Format.general (/Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/manifest-revision-webpack-plugin/format.js:67:23)
[WEBPACK]     at Compiler.<anonymous> (/Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/manifest-revision-webpack-plugin/index.js:166:53)
[WEBPACK]     at Compiler.applyPlugins (/Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
[WEBPACK]     at Watching._done (/Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/webpack/lib/Compiler.js:98:16)
[WEBPACK]     at /Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/webpack/lib/Compiler.js:73:18
[WEBPACK]     at Compiler.emitRecords (/Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/webpack/lib/Compiler.js:367:37)
[WEBPACK]     at /Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/webpack/lib/Compiler.js:56:19
[WEBPACK]     at /Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/webpack/lib/Compiler.js:360:11
[WEBPACK]     at next (/Users/khoffrath/projects/tmp/flask-scaffolding/umb/node_modules/webpack/node_modules/tapable/lib/Tapable.js:218:11)
[WEBPACK]
[WEBPACK] npm
[WEBPACK]  ERR! Darwin 16.7.0
[WEBPACK] npm
[WEBPACK]  ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "webpack-dev-server"
[WEBPACK] npm ERR! node v4.8.4
[WEBPACK] npm
[WEBPACK]
[WEBPACK] ERR! npm  v2.15.12
[WEBPACK] npm
[WEBPACK]  ERR!
[WEBPACK]  code ELIFECYCLE
[WEBPACK] npm ERR!
[WEBPACK]  umb@1.0.0 webpack-dev-server: `NODE_ENV=debug ./node_modules/.bin/webpack-dev-server --port 2992 --hot --inline`
[WEBPACK] npm ERR! Exit status 1
[WEBPACK] npm ERR!
[WEBPACK] npm ERR! Failed at the umb@1.0.0 webpack-dev-server script 'NODE_ENV=debug ./node_modules/.bin/webpack-dev-server --port 2992 --hot --inline'.
[WEBPACK] npm ERR! This is most likely a problem with the umb package,
[WEBPACK] npm ERR! not with npm itself.
[WEBPACK] npm ERR!
[WEBPACK]  Tell the author that this fails on your system:
[WEBPACK] npm ERR!     NODE_ENV=debug ./node_modules/.bin/webpack-dev-server --port 2992 --hot --inline
[WEBPACK] npm ERR!
[WEBPACK]  You can get information on how to open an issue for this project with:
[WEBPACK] npm ERR!
[WEBPACK]      npm bugs umb
[WEBPACK] npm
[WEBPACK] ERR! Or if that isn't available, you can get their info via:
[WEBPACK] npm ERR!
[WEBPACK] npm
[WEBPACK]  ERR!     npm owner ls umb
[WEBPACK] npm ERR! There is likely additional logging output above.
[WEBPACK]
[WEBPACK] npm ERR! Please include the following file with any support request:
[WEBPACK] npm ERR!     /Users/khoffrath/projects/tmp/flask-scaffolding/umb/npm-debug.log
[WEBPACK] npm run webpack-dev-server exited with code 1

It seems to crash in the module manifest-revision-webpack-plugin in file format.js line 52: https://github.com/nickjj/manifest-revision-webpack-plugin/blob/master/format.js#L52 but my Node.js and JavaScript knowledge is insufficient to debug this problem, any help is greatly appreciated.

*My environment*
- MacOS 10.12.6
- Python 3.6.2
- Node 4.8.4
- npm 2.15.12

*Steps to reproduce the problem*
```
cookiecutter https://github.com/sloria/cookiecutter-flask/ (using umb as projectname)
mkvirtualenv umb --python=`which python3.6`
pip install -r requirements/dev.txt
npm install
export FLASK_APP=`pwd`/autoapp.py
export FLASK_DEBUG=1
export WEBPACK_MANIFEST_PATH=`pwd`/umb/webpack/manifest.json
```
`npm run-script build` (see https://github.com/sloria/cookiecutter-flask/issues/189#issuecomment-320909984)

After this command the file umb/webpack/manifest.json exists and contains the following elements:
```
{
  "assets": {
    "main_js.js": "main_js.0662802407e6e6d98f95.js",
    "main_js.map": "main_js.0662802407e6e6d98f95.js.map",
    "main_css.js": "main_css.0662802407e6e6d98f95.js",
    "main_css.css": "main_css.0662802407e6e6d98f95.css",
    "main_css.map": "main_css.0662802407e6e6d98f95.css.map"
  },
  "publicPath": "/static/build/"
}
```

`npm start`

**Comment by conloos** [comment]
Hi,

i have the same Problem on Kubuntu 17.04.

**Comment by vlasy** [comment]
I just had the exact same problem in my Docker container (Ubuntu 16.04).

The problem was that I had and old version of Nodejs installed (4.2.6) in the container. I updated it to 6.11.4 with the instructions from https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions.

Problem fixed.

**Comment by sloria** [comment]
Thanks for your insight @vlasy . 

If you are having this problem, please try upgrading your NodeJS version to at least 6.0.

**Comment by conloos** [comment]
Hi,

i confirm, that this fix my Problem, too.
