### ISSUE TITLE
Circular import error when trying to customize SQLAlchemy at initialization

### ISSUE THREAD

**Issue by mattdavis1121** [sloria/cookiecutter-flask#220]
The Flask-SQLAlchemy docs show options for configuring a custom query class [here](http://flask-sqlalchemy.pocoo.org/2.2/customizing/#query-class). The relevant example code is here:

```python
from flask_sqlalchemy import BaseQuery, SQLAlchemy

class GetOrQuery(BaseQuery):
    def get_or(self, ident, default=None):
        return self.get(ident) or default

db = SQLAlchemy(query_class=GetOrQuery)
```

I wrote my custom class in app.app.database, and I'd like to import that class into app.app.extensions so it's available for initialization, but this causes a circular import error. Here's an abbreviated version of my code:

```python
# database.py
from flask_sqlalchemy import BaseQuery

class CustomQueryClass(BaseQuery):
    def custom_method(self):
        pass
```

```python
# extensions.py
from flask_sqlalchemy import SQLAlchemy
from app.database import CustomQueryClass

db = SQLAlchemy(query_call=CustomQueryClass)
```

This errors on run. `ImportError: cannot import name CustomQueryClass`

Anyone else encountered this problem? Any advice? I've tried a few workarounds. The most promising of these is at the bottom of the docs page I linked.

```python
class MyModel(db.Model):
    query_class = GetOrQuery
```

This works for all the models I do this on, but not on any relationships to these models, which is really the functionality I want.

Thanks,

Matt Davis

**Comment by sloria** [comment]
The problem is that `database.py` imports `extensions.py` and your code above makes `extensions.py` import `database.py`.

To get rid of the circular import, you'll need to put `CustomQueryClass` in a different module. One way to do this would be to make `database` into a folder like so:

```
database
├── __init__.py
├── base.py  # contains Model
├── mixins.py
├── query.py   # contains you custom query class
└── utils.py
```

Then you can import CustomQueryClass:

```python
# extensions.py
from flask_sqlalchemy import SQLAlchemy
from app.database.query import CustomQueryClass

db = SQLAlchemy(query_call=CustomQueryClass)
```

**Comment by mattdavis1121** [comment]
That fixed it. Thanks, man.
