### ISSUE TITLE
Single table inheritance and SurrogatePK issue when upgrading Flask-SQLAlchemy >2.3

### ISSUE THREAD

**Issue by bmjjr** [sloria/cookiecutter-flask#230]
My app uses quite a bit of single table inheritance in models that include the SurrogatePK mixin in database.py. I ran into some pain when upgrading to latest Flask-SQLAlchemy==2.3.2 with a traceback:
```
"Can't place __table_args__ on an inherited class "
sqlalchemy.exc.ArgumentError: Can't place __table_args__ on an inherited class with no table.
```
Finally tracked the issue down to `__table_args__ = {'extend_existing': True}` in the SurrogatePK class in database.py [found here](https://github.com/sloria/cookiecutter-flask/blob/03a9275d05dadc31bb7fd8ce1ad2f5686dbce015/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/database.py#L50).  Bottom line is that I removed it and now all my tests pass.  

[The SQLAlchemy docs on extend_existing](http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.Table.params.extend_existing) do not make it super clear to me why this should be set at all in this mixin from the start. It seems like a setting that developers should find and deal with when they figure out it actually needs to be explicitly set, due to their specific needs.

**Comment by adamrt** [comment]
Can you post the relevant parts of your model you are using SurrogatePK on? The extend_existing usage makes sense base on the extened_existing documentation:

> When True, indicates that if this Table is already present in the given MetaData, apply further arguments within the constructor to the existing Table.

If you look at the Role model that's included in the cookiecutter as an example, you see they use SurrogatePK but the Role class specifies __tablename__.

```
class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
```

**Comment by bmjjr** [comment]
What broke on the SQLAlchemy 2.3.2 upgrade is specifying `__table_args__ = {'extend_existing': True}` in SurrogatePK and then mixing that into a base table class and then subclassing that base table class in a single inheritance relationship. Specifying `__tablename__`  did not cause any problem and is still fine to do that in the base table class. For example, this breaks with  `__table_args__ = {'extend_existing': True}` specified in SurrogatePK but works fine after getting rid of it. So it is not very robust to include in a mixin if it breaks single table inheritance for any class that uses the mixin. It should probably be set in the class that inherits the mixin, when the programmer decides it needs set in that particular class.

```
class Organization(SurrogatePK, Model, AuditMixin):
    """A company for the database"""
    __tablename__ = 'organizations'

    name = Column(db.Unicode(128), nullable=False)
    website = Column(db.Unicode(128))
    type = Column(db.Unicode(50), nullable=False)

    __mapper_args__ = {
        'polymorphic_identity': 'organizations',
        'polymorphic_on': db.case([
                        (type == "clients", "clientco"),
                        (type == "suppliers", "supplierco"),
                    ], else_="organizations")
    }

class ClientCompany(Organization):
    """A client customer"""
    client_type = Column(db.Unicode(50))

    __mapper_args__ = {
        'polymorphic_identity': 'clientco',
    }

class SupplierCompany(Organization):
    """A supplier."""
    supplier_type = Column(db.Unicode(50))
    avl_status = Column(db.Unicode(50))

    __mapper_args__ = {
        'polymorphic_identity': 'supplierco',
    }

```

**Comment by sloria** [comment]
Closing, as this issue is stale. Feel free to reopen or comment if there's still an issue.

**Comment by sergioisidoro** [comment]
This issue is still relevant. Is there a fix for this?
