### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by rlam3** [sloria/cookiecutter-flask#232]
I cloned the repository in hopes of running flask shell but the following error occured.

Do we have to rename the whole app? Thanks! 

```
    from {{cookiecutter.app_name}}.app import create_app
         ^
SyntaxError: invalid syntax
```

**Comment by adamrt** [comment]
You must install the project via cookiecutter, not by cloning the repository. Look at the first part of the README

**Comment by sloria** [comment]
Correct; you must use this together with `cookiecutter`.
