### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by akkatracker** [sloria/cookiecutter-flask#266]
Is there any intention for this repo to be upgraded to the latest release of Bootstrap, [Bootstrap 4](http://getbootstrap.com/)?

**Comment by sloria** [comment]
Yeah, it would be great to upgrade. I don't have the bandwidth to do this at the moment, but I would certainly review and merge a PR =)

**Comment by dasdachs** [comment]
If it's still unasigned I'll give it a go.

![screen shot 2018-02-05 at 17 45 57](https://user-images.githubusercontent.com/12150735/35817100-c197593a-0a9c-11e8-80e7-55de879e97c0.png)

**Comment by sloria** [comment]
@dasdachs All yours!

**Comment by adawalli** [comment]
This has been addressed in #313 - feel free to provide feedback

**Comment by sloria** [comment]
This is done. Thanks @adawalli and @Hiyorimi .
