### ISSUE TITLE
No CSS,JS created

### ISSUE THREAD

**Issue by antani** [sloria/cookiecutter-flask#29]
When the templated is rendered the first time, no CSS or JS files are created inside - public/css/common.css and public/js/common.js

Firebug shows that the they are served from /static/js and /static/css instead. How to make sure that the changed JS gets reflected in the app ?

**Comment by kleino** [comment]
```
assets.py
css = Bundle(
    ....
    output="public/css/common.css"
)
public/views.py
blueprint = Blueprint('public', __name__, static_folder="../static")
````
Flask-Webassets allows to use blueprint names in the "output" parameter and replaces the name with the static folder of the blueprint. For this template, there is a blueprint named "public", so Webassets uses the static folder defined here and replaces it with `static_folder`. If you wanted to use the "static\public" folder, you could write public twice, e.g. `output="public/public/css/common.css"` But I suppose there has to be a better solution.

**Comment by sloria** [comment]
Closing this, as this has gone stale. Feel free to reopen if this is still an issue.
