### ISSUE TITLE
Encode on check password

### ISSUE THREAD

**Issue by DiegoPires** [sloria/cookiecutter-flask#33]
Hi man, on the check_password method of the User models I need to encode the password, otherwise I was receiving an error here:

Before:

```
def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)
```

After:

```
def check_password(self, value):
    return bcrypt.check_password_hash(self.password.encode('utf-8'), value)
```

That's just me?

**Comment by sloria** [comment]
That shouldn't be necessary with the newer versions of Flask-Bcrypt, which will encode passwords if needed. What version of Flask-Bcrypt are you using? You can check by running the following:

```
pip freeze | grep "Flask-Bcrypt"
```

**Comment by sloria** [comment]
Closing for now; please reopen if this is still an issue.
