### ISSUE TITLE
CSRF on login

### ISSUE THREAD

**Issue by DiegoPires** [sloria/cookiecutter-flask#34]
When trying to login with the header form, I receive an error that the CSRF was not been sent, needed to change in the nav.html

```
{{ form.hidden_tag() }}
```

To this:

```
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
```

And put on the app.py:

```
flask_wtf.CsrfProtect(app)
```

Like is been said [here](https://flask-wtf.readthedocs.org/en/latest/api.html#module-flask_wtf.csrf)

**Comment by sloria** [comment]
+1 for adding CSRF protection. @DiegoPires would you like to send a pull request adding those changes?

**Comment by itsrifat** [comment]
The register template still contains `{{ form.hidden_tag() }}` and isn't working for me. Changing it to `<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>` as above works though

**Comment by Shonin** [comment]
Is there a reason CSRF if set to disabled for the register form in the view? [Line in question is here](https://github.com/sloria/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/public/views.py#L49)

**Comment by sloria** [comment]
@shonin Sorry for the delayed response. There's no good reason for CSRF protection to be disabled on the register form. Fixed now!
