### ISSUE TITLE
Run tests in parallel using pytest-xdist

### ISSUE THREAD

**Issue by the-shank** [sloria/cookiecutter-flask#37]
Is it possible to modify the fixtures so that the tests can be run in parallel using pytest-xdist plugin. Currently the way session (and db) is created, they don't play well with running the tests in parallel.

**Comment by sloria** [comment]
If someone wants to look into this, I would gladly review and merge a PR.

**Comment by sloria** [comment]
Closing this as this issue has gone stale. Feel free to reopen if it's still an issue.
