### ISSUE TITLE
Impossible to install from cpanel

### ISSUE THREAD

**Issue by JohannCR** [sloria/cookiecutter-flask#461]
Can't figure out how to install it from cpanel... dependencies are easily installed via pip but 
cookiecutter https://github.com/sloria/cookiecutter-flask.git
cannot be executed from cpanel because of the ":" character
Is there a way to copy the files manually to the server and launch the install locally ? There is no setup.py file...
Thanks

**Comment by oerd** [comment]
Cookiecutter as a dependency is only required *once* during generation (i.e. it's a development dependency).

In your case - if you really want to stay with the cpanel environment - I suggest that you generate the project on your local machine and then _sync_ the files to your server.

**Comment by JohannCR** [comment]
Thanks for your answer !
I've successfully generated the project locally and uploaded the files, but I'm having another error : 
File "/home/nlovma/Moniteur/settings.py", line 16, in <module>
    SQLALCHEMY_DATABASE_URI = env.str('**************')
  File "/home/nlovma/virtualenv/Moniteur/3.7/lib/python3.7/site-packages/environs.py", line 47, in method
    'Environment variable "{}" not set'.format(proxied_key or parsed_key)
environs.EnvError: Environment variable "**************" not set

It is not linked to my db config since it happens for any db URL (for any string even).
Plus, should this be in clear (I know nothing about security, except that sensible stuff like that should be encrypted, shouldn't it ? anyway not important for my use case ^^).
Thanks for any pointers
(should I open another issue and close that one instead ?)

**Comment by sloria** [comment]
@JohannCR You need to fix the line

```
SQLALCHEMY_DATABASE_URI = env.str('SQLALCHEMY_DATABASE_URI')
```

Then set the SQLALCHEMY_DATABASE_URI environment variable.
