### ISSUE TITLE
Customize path to .cookiecutterrc

### ISSUE THREAD

**Issue by nfarrar** [sloria/cookiecutter-flask#47]
Any chance cookiecutter could allow us to read from a cookiecutterrc file stored in another location (i.e. the XDG default: `~/.config/cookiecutter/config`). I *really* like having my home uncluttered - and lately have been trying to move my configuration files out as much as possible.

This could be done several simple ways:

1. Make cookiecutter check (by default) the current location & for an XDG compatible configuration file.
2. Add a *config* flag (`cookiecutter <...> --config=~/.config/cookiecutter/config`)
3. Read an environment variable, if it exists:

```
import os
config_file = os.getenv('COOKIECUTTER_CONFIG', '~/.cookiecutterrc`)
```

**Comment by kxi** [comment]
I don't think this is an issue with cookiecutter-flask, this is just to do with cookiecutter?

**Comment by nfarrar** [comment]
Sorry, I apologize. I meant to post this on the cookiecutter issue tracker! Closing ...
