### ISSUE TITLE
Question: Any interest in putting together a premium version for sale on SugarKubes?

### ISSUE THREAD

**Issue by wrannaman** [sloria/cookiecutter-flask#473]
Hi @sloria , congrats on the traction! Would you be interested in putting together a premium version of this repo to sell on [SugarKubes](https://sugarkubes.io)? It's a code and container marketplace I'm putting together.

**Comment by sloria** [comment]
No thank you, I have no interest in monetizing this project. Thanks anyway for reaching out.

**Comment by wrannaman** [comment]
no worries, thanks for the response. If you do have other projects in mind I'd love to hear about the use cases!
