### ISSUE TITLE
ValueError: path is on drive e:, start on drive C:

### ISSUE THREAD

**Issue by guyskk** [sloria/cookiecutter-flask#58]
This occurred on Windows when I visit http://127.0.0.1:5000/

flask_debugtoolbar\panels\versions.py", line 51, in content

line 12 
relative = os.path.relpath(location, python_lib)  

and
location is `C:\\Python27\\Lib\\site-packages`
python_lib is `e:\\work\\py\\flask-restaction`

> os.relpath _does_ give you a relative path between two directories.
> 
> The problem you are encountering is that, on Windows, a relative path
> doesn't even _exist_ if the two directories are on different drives

**Comment by guyskk** [comment]
Anyone can give me some advices?

**Comment by sloria** [comment]
this appears to be an issue with flask_debugtoolbar. Please report the issue there if this problem still  exists.
