### ISSUE TITLE
Bootstrap glyphicon font unavailable from minified CSS

### ISSUE THREAD

**Issue by dannyferreira** [sloria/cookiecutter-flask#59]
This is not an issue when running against the DevConfig, since the CSS is not minified in that case.

When the Bootstrap CSS is minified and bundled with other CSS, it is effectively 'moved' to another location relative to the bootstrap fonts.

I'm not sure what a good solution for this problem is.

**Comment by hypebeast** [comment]
One solution would be to include an extra stylesheet in production mode:

```
{% if config.ENV == "prod" %}
    {% assets "css_prod" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
  {% endif %}

  {% block css %}{% endblock %}
```

And the production stylesheet contains the following:

```
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('../libs/bootstrap/fonts/glyphicons-halflings-regular.eot');
  src: url('../libs/bootstrap/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../libs/bootstrap/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

It's not an elegant solution, but it works. Right now I don't know a better way to do it.

**Comment by Tafkas** [comment]
Is this still valid after #183 has been merged?

**Comment by sloria** [comment]
Good catch @Tafkas . This should no longer be an issue.
