### ISSUE TITLE
Password as plaintext after update

### ISSUE THREAD

**Issue by LukasSliacky** [sloria/cookiecutter-flask#63]
When i create new user:

`User.create(username='username', email='email@email.sk', password='password')`

is password pretty hashed, but when update this user:

```
user = User.query.get(1)
user.update(username='username', email='email@email.sk', password='password'
```
password is stored as plain text: "password".

**Comment by dyzajash** [comment]
Because you update it wrong. 

user = User.query.get(1)
user.set_password(password=password)
user.update(username='username', email='email@email.sk')

**Comment by LukasSliacky** [comment]
Ou, i forget... 
Sorry, my Bad.

**Comment by caffeinatedMike** [comment]
@LukasSliacky @FunnyScarf I address this issue with #1195 in order to alleviate any potential security issues should someone forget to call the separate method to encode a password. Once merged, you can update the password field just the same as any other field, no special handling needed.
