### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by jayfk** [sloria/cookiecutter-flask#65]
I have a working docker configuration lying around using docker-compose for dev/prod. If there's any interest in that, I'd wrap it up and submit a pull request.

**Comment by sloria** [comment]
I'd certainly review and merge a PR for this!

**Comment by keybits** [comment]
This would be a great addition. If it could work similarly to cookiecutter-django docker deployment even better :-) Happy to help test.

**Comment by aliavni** [comment]
I would love to see this as well since I put some time "dockerizing" this. Happy to help test as well.

**Comment by MCWEMA** [comment]
It'll be a great addition

**Comment by rustanacexd** [comment]
that would be awesome!

**Comment by freddystban** [comment]
I've been working on extending this project to add docker support, it is a work in progress very much so but it is working. It has a postgres db, nginx load balancer, gunicorn wsgi, I'm wondering if I could get some feedback on it. I've never contributed to open source before btw. I've forked the project and created a branch docker-support. What would be the best way to get some eyes on it? thanks.

**Comment by sloria** [comment]
@freddystban Thanks for working on this. Sounds like you're making good progress.

Best way to get eyes on your branch would be to send a PR, which you can do through the GitHub UI. When you create the PR, just put "WIP" at the beginning of the PR title to indicate that it's a work in progress.

**Comment by freddystban** [comment]
Can I get some eyes on this https://github.com/sloria/cookiecutter-flask/pull/272 whenever someone has time, thank you.

**Comment by vnarayan13** [comment]
He seemed to be on a breakthrough. poor kid.

**Comment by mrkmcknz** [comment]
Is anyone else working on this? What happened with #272 ?

**Comment by jamescurtin** [comment]
Issue resolved by #483.

Let me know if you have any feedback!
