### ISSUE TITLE
Is there a step by step guide?

### ISSUE THREAD

**Issue by bsamadi** [sloria/cookiecutter-flask#73]
I was wondering if there is a step by step guide on how to get this template online. It seems that installing the requirements alone is not enough. I am a newbie and this is my first attempt to use cookiecutter.

**Comment by pbreit** [comment]
Me too. I got the requirements installed but no further.

**Comment by Shonin** [comment]
@bsamadi  @pbreit 
can you explain your problem a bit more, post your error messages, etc?

**Comment by bsamadi** [comment]
@Shonin My problem is that I have some experience with WordPress and similar content management systems. However, I have no idea what I should do to get the cookiecutter-flask up and running. I execute the cookiecutter command and it creates a bunch of files. What is next?

**Comment by Shonin** [comment]
@bsamadi if your experience level ends at WordPress then you will need to train on Python for a while before this is a manageable project for you. This repo is meant for those who already have a strong grasp on the Python language, as well as a reasonable amount of familiarity with the Flask micro-framework. 

If you want to dive into this from scratch, there are a lot of free resources out there. I recommend looking at the syllabus for this nanodegree: [Full Stack Web Developer](https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd004 ). You can take all those "Supporting Courses" for free. They will teach you Python and Flask.

**Comment by beardedeagle** [comment]
If that is all you have for experiance, you could potentially look at Django-CMS or Quokka CMS

**Comment by bsamadi** [comment]
@Shonin @beardedeagle That's not all my experience. I was just giving WordPress as an example. I managed to run the Flask example with the help of someone who is familiar with the context. I was looking for a step by step guide to get a newbie to run an example and then dive deeper where necessary. Thanks for your comments.

**Comment by bsamadi** [comment]
I tried a few Flask examples and I found cookiecutter-Flask-Foundation better structured.

**Comment by artburkart** [comment]
For those who are brand new to python and just want to see the thing work. Here's how I get it to go:

```
# Assuming you're on an Apple
brew install postgresql
cookiecutter https://github.com/sloria/cookiecutter-flask.git
# Let's assume I named it test_app
cd test_app
virtualenv venv
. venv/bin/activate
pip install -r requirements.txt
python manage.py db init
python manage.py db migrate
python manage.py db upgrade
python manage.py server
open localhost:5000
```

That should, at the very least, get you started playing with it.

**Comment by sloria** [comment]
As mentioned above, the instructions for starting the project are included in the README for generated projects. If you think they can be improved, please send a PR =)

**Comment by luoenzhen** [comment]
Read the app.py which explains many things.
