### ISSUE TITLE
Switching mysql for postgresql

### ISSUE THREAD

**Issue by beardedeagle** [sloria/cookiecutter-flask#74]
How would one change out the database engine used from postgresql to mysql for prod? Basically to what extent is postgre tied into the application so one would know what all needs to be updated to support alternative engines.

**Comment by iandouglas** [comment]
For that matter, can cookiecutter prompt the user which database they want to use and set the database configuration appropriately? It's already marked as a TODO in the code here:
https://github.com/sloria/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/settings.py#L25

Prompting the user for the name of the database type, database name, db user/pass, etc should be easy enough?

**Comment by beardedeagle** [comment]
It _LOOKS_ like all you need to do is change the db url and remove the psycopg2 dep afaik. When I do this the site still works and I am able to register and log in. Just making sure this is all so that I don't run into any unexpected surprises.

**Comment by sloria** [comment]
cookiecutter-flask will only support postgres out-of-the-box for now. As previous posters have mentioned, switching engines should be as simple as changing the DB URI and updating the dependencies.
