### ISSUE TITLE
Upgrade to Flask 0.11

### ISSUE THREAD

**Issue by vamega** [sloria/cookiecutter-flask#76]
Part of this could be to replace the dependency on Flask-Script with the new Flask CLI.

**Comment by sloria** [comment]
Yes, this would be great. I would definitely appreciate a PR helping out with this.

**Comment by vamega** [comment]
This might be held up until Flask-Migrate has a story of how to use the Flask CLI.

https://github.com/miguelgrinberg/Flask-Migrate/issues/114

**Comment by miguelgrinberg** [comment]
@vamega Flask-Migrate 2.0 supports the new Flask CLI.

**Comment by Jaza** [comment]
I've implemented a fair bit of the changes needed for this in #78 - help and feedback welcome.
