### ISSUE TITLE
Problem with registering error_handlers

### ISSUE THREAD

**Issue by on3iro** [sloria/cookiecutter-flask#77]
Hey,

I am currently working on my own cookiecutter and use your version as a foundation. While doing so I came across a possible error inside your app.py (I might be wrong here, though). 
Your app tries to register the error handlers with:

``` python
app.errorhandler(errcode)(render_error)
```

This did not work for me, though. I looked at the man pages and changed the code to the following:

``` python
app.register_error_handler(errcode, render_error)
```

**Comment by sloria** [comment]
Both ways should work, given that you are using a Flask version >= 0.7.
