### ISSUE TITLE
Can't running IDE debugger. Database connection issue when modifying autoapp.py

### ISSUE THREAD

**Issue by tomtom92** [sloria/cookiecutter-flask#86]
This is more of a question rather than an issue. I would like to use the PyCharm debugger, but in order to do this, I should run autoapp.py through the IDE interface, not call `flask run` from the command line. However, upon adding the line `app.run()` to autoapp.py, when attempting to login, I receive the following error.

`OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432?`

This seems to be common (not just to this project). Do I need to adjust my database in order to run the application directly from `autoapp.py`?

Thanks!

**Comment by jcass77** [comment]
I use PyCharm to debug my Flask applications. It should not be necessary to introduce any config or code changes to do this.

All you need to do is [create a debug configuration](https://www.jetbrains.com/help/pycharm/2016.2/creating-and-editing-run-debug-configurations.html), and then set the necessary ``Environment variables`` to replicate what you have on the command line.

You can, and should, then still make use of ``flask run`` to launch your app by specifying the path to your Flask binary in ``Script`` and simply setting ``Script parameters`` to 'run'.

**Comment by tomtom92** [comment]
Fantastic. I think I understand how this works better now. This seemed to work. Another quick followup question, how are the commands within the command file different from running `flask` with an argument after it? I see that these are click commands (and probably not flask commands).

Thanks
